services:
  dns:
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      - DEBUG=true
    env_file:
      - .env
    command: ["python", "-u", "dns.py"]
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  exporter:
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      SWARM_NODE_ID: 'umfh3tmcs0v9qyo7bkwsvlhxt'
    env_file:
      - .env
    command: ["python", "-u", "exporter.py"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nodes:
    build:
      context: ../
      dockerfile: Dockerfile
    env_file:
      - .env
    command: ["python", "-u", "nodes.py"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  merger:
    build:
      context: ../
      dockerfile: Dockerfile
    env_file:
      - .env
    command: ["python", "-u", "merger.py"]